{
  # +++++++++++ read  CLI configs ++++++++++
  "layer": -1,
  "treatment": True,
  "analysis": False,
  "print_config": True,
  # default
  "topk": True,
  "distribution": False,
  "embedding_summary": False,
  "getting_counterfactual": False,
  "traced": False, 
  "debias": False,
  "get_prediction": True,
  "dev-name": "mismatched",
  "weaken": null,
  "neuron_group": null,
  
  "model_name": "../bert-base-uncased-mnli/",
  "is_group_by_class": False,
  "is_averaged_embeddings": True,
  "intervention_type": "weaken",
  "upper_bound": 95,
  "lower_bound": 5,
  "seed": 42,
  "collect_representation": True,
  "DEBUG": True,
  "debug": False, 
  
  # compute nie scores
  "num_samples": 300,
  "label_maps": {"contradiction": 0 , "entailment" : 1, "neutral": 2 },
  "layers": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  "heads": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        
  # experiment set 
  "k":  null, 
  "num_top_neurons": null, 
  "range_percents": True, 
  'neurons': True, 
  "dev_path": "../debias_fork_clean/debias_nlu_clean/data/nli/",
  "exp_json": "multinli_1.0_dev_matched.jsonl",
  "dev_json": {},

  # data settings
  "counterfactual_paths": [],
  "NIE_paths": [],
  "is_NIE_exist": [],
  "is_counterfactual_exist": [],
  
  # optimizer settings
  # range 0.0 to 0.10, step = 0.01
  "percent": {
    "low": 0.0, 
    "high": 0.1,
    "step": 0.01,
    "size": 50,
    "mode": 0o666,
    "acc": {}
    },

  # range 0 to 1, step = 0.1
  "epsilons": {
    "low": 0, 
    "high": 1,
    "step": 0.1,
    "size": 50,
    "mode": 0o666,
    "acc": {}
    },
  
  "single_neuron": False,

  # evaluate hans
  "eval": {
    "do": 'High-overlap',
    "layer": 1,
    "debug": False,
    "all_layers": True,
    "intervention_mode": "Intervene"
    },

  # uppper bound test on test set
  
  # use to read prediction txt files
  "prediction_path": '../pickles/prediction/',
  "evaluations":  {},
  "to_text": True,
  "get_result": False,
  "save_rank": True,

  # neurons components
  "attention_components": 3,
  "nums": {}
}

#current jobs : 23185



    
         