#!/bin/bash -l
#SBATCH --output=slurm-%j.out
#SBATCH --job-name=love_DPK
#SBATCH --mem=64GB
#SBATCH --time=48:0:0     # Runing time 
#SBATCH --gpus=1
#SBATCH --partition=gpu-cluster
#SBATCH --account=scads

source /ist/users/sitipornl/anaconda3/bin/activate 
source /ist/users/sitipornl/anaconda3/bin/activate  /ist/users/sitipornl/anaconda3/envs/combine_env/
export PYTHONNOUSERSITE=True

python trainer_reweight_fever.py